// <auto-generated />
namespace JamventionDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixIdentity4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixIdentity4));
        
        string IMigrationMetadata.Id
        {
            get { return "202011241810371_fixIdentity4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
