INSERT INTO JAM.GuestRoles
 
(RoleName)
 
VALUES
 
('Participant'),
('Model'),
('Teacher'),
('Catering'),
('Staff'),
('Special'),
('Organizer');



INSERT INTO JAM.TimeSlots (Day, StartTime, EndTime)
VALUES
('2020-10-16', '0:18:30', '0:22:30'),
('2020-10-16', '0:15:30', '0:18:00'),
('2020-10-16', '0:08:30', '0:12:00'),
('2020-10-17', '0:09:00', '0:12:00'),
('2020-10-17', '0:08:30', '0:12:30'),
('2020-10-17', '0:13:30', '0:17:00'),
('2020-10-17', '0:13:30', '0:17:30'),
('2020-10-17', '0:18:30', '0:22:30'),
('2020-10-18', '0:08:30', '0:12:00'),
('2020-10-18', '0:09:00', '0:12:00'),
('2020-10-18', '0:08:30', '0:12:30'),
('2020-10-18', '0:13:30', '0:17:00'),
('2020-10-18', '0:13:30', '0:17:30');

INSERT INTO JAM.Locations
 
(LocationName)
 
VALUES
 
('Hen House'),
('Cows Shed'),
('Swallows Nest'),
('Piggery'),
('The Stable');


INSERT INTO Jam.RoomTypes
 
(TypeName)
 
VALUES
 
('Rabbit'),
('Sheep'),
('Duck'),
('Piglet'),
('Pig'),
('Rooster'),
('At Piggery');

Insert INTO Jam.Rooms
(Beds)
VALUES
(4),
(4),
(4),
(4),
(5),
(5),
(5),
(5),
(4),
(4),
(6),
(4),
(4),
(4),
(5),
(5),
(5),
(5),
(5),
(5),
(2),
(2),
(2),
(2),
(2),
(2),
(2),
(4),
(2),
(3);
Insert INTO Jam.LocalRooms
(RoomID, RoomTypeID, RoomCode, RoomColor)
VALUES
(1, 1, '1-1', 'Pink'),
(2, 1, '1-2', 'Yellow'),
(3, 1, '1-3', 'Purple'),
(4, 1, '1-4', 'Blue'),
(5, 2, '2-1', 'Blue'),
(6, 2, '2-2', 'Yellow'),
(7, 2, '2-3', 'Pink'),
(8, 2, '2-4', 'Purple'),
(9, 3, '3-1', 'Purple'),
(10, 3, '3-2', 'Yellow'),
(11, 3, '3-3', 'Pink'),
(12, 3, '3-4', 'Blue'),
(13, 4, '4-1', 'Blue'),
(14, 4, '4-2', 'Purple'),
(15, 4, '4-3', 'Yellow'),
(16, 4, '4-4', 'Pink'),
(17, 5, '5-1', 'Pink'),
(18, 5, '5-2', 'Yellow'),
(19, 5, '5-3', 'Purple'),
(20, 5, '5-4', 'Blue'),
(21, 6, '0', 'Purple'),
(22, 6, '1', 'Blue'),
(23, 6, '1', 'Yellow'),
(24, 6, '2', 'Blue'),
(25, 6, '2', 'Yellow'),
(26, 7, '', '')
;
INSERT INTO Jam.OtherRooms
(RoomID, RoomDescription)
VALUES
(27, 'Suiskens; Kamer Ouders'),
(28, 'Suiskens; Studio'),
(29, 'Suiskens; Kantoor Willy'),
(30, 'Suiskens; Kamer Bryant');

Insert INTO JAM.TicketTypes
(TicketName, TicketPrice, OnFriday, OnSaturday, OnSunday)
VALUES
('JAM Ticket', 280, 1, 1, 1),
('JAM 4-Beds Ticket', 265, 1, 1, 1),
('Early Bird JAM Ticket', 255, 1, 1, 1),
('Gift Jam Ticket', 0, 1, 1, 1),
('8-Hour Ticket', 165, 0, 1, 0),
('8-Hour Gift Ticket', 0, 0, 1, 0),
('6-Hour Ticket', 125, 0, 0, 1),
('6-Hour Gift Ticket', 0,  0, 0, 1);

INSERT INTO Jam.Nationalities
 
(CountryName)
 
VALUES
 
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burma'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Central Africa'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo'),
('Costa Rica'),
('Cote dIvoire'),
('Crete'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominican Republic'),
('East Timor'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia, The'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guadeloupe'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Holy See'),
('Honduras'),
('Hong Kong'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Israel'),
('Italy'),
('Ivory Coast'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Korea, North'),
('Korea, South'),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Macau'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('North Korea'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Saint Lucia'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Scotland'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Korea'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Tibet'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe');
